# Permalinks
permalink:        pretty

# Setup
title:            'Left Brain Dominant'
tagline:          'Analytical'
description:      'A blog about technical and analytical topics.'
markdown:         kramdown
url:              https://leftbraindominant.com
baseurl:          /

author:
  name:           'Prateek'
  url:            prateek.app

paginate:         1

# Custom vars
version:          1.0

github:
  repo:           https://github.com/random-cup/left-brain
